# Site Settings
title:               Josh Soucie
tagline:             A Not-Yet-World-Renowned Entrepreneur
description:
baseurl:            #"/jblog"
url:                #"https://www.joshsoucie.com"
github:
  url:               "https://js-bone21.github.io/jblog"
author:
  name:              "Joshua Soucie"
  email:             "jlsoucie21@gmail.com"
  twitter:           "josh_soucie"
  instagram:         "joshsoucie"
  github:            "js-bone21"
  facebook:          "jlsoucie"
  linkedin:          "joshuasoucie"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
