# Site Settings
title:              Joshua Soucie
tagline:            Engineer, Hacker, Entrepreneur, Globetrotter
description:
baseurl:            "/jblog"
url:                "https://www.joshsoucie.com/jblog"
github:
  url:               "https://js-bone21.github.io/jblog"
author:
  name:              "Joshua Soucie"
  email:             "jlsoucie21@gmail.com"
  twitter:           "josh_soucie"
  instagram:         "joshsoucie"
  github:            "js-bone21"
  facebook:          "jlsoucie"
  linkedin:          "joshuasoucie"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
